export const privacy_text = (
  <>
    <div>
      <strong>Privacy Policy for Recenter</strong>
    </div>
    Recenter is a Chrome extension that helps you stay focused and productive
    while browsing the web. We take your privacy seriously, and this policy
    explains how we collect, use, and protect your data.
    <div>
      <strong>What Data We Collect</strong>
    </div>
    Recenter collects and locally stores the following data:
    <ul>
      <li>URLs you visit and the time spent on those sites</li>
      <li>
        If you provide an OpenAI API key, textual summaries of your daily and
        hourly browsing generated by OpenAI's API
      </li>
      <li>
        All of this data is stored only locally on your browser - it is not sent
        to any servers controlled by Recenter or third parties.
      </li>
    </ul>
    <div>
      <strong>Use of OpenAI API (Optional)</strong>
    </div>
    You have the option to enter an OpenAI API key into Recenter. If you do:
    <ul>
      <li>Your key is stored locally in your browser</li>
      <li>
        Recenter will query OpenAI's API to categorize sites if not on our
        pre-tagged list
      </li>
      <li>
        Recenter will send summarized browsing data to generate textual
        daily/hourly summaries
      </li>
      <li>
        From what we can tell from their fine-print, this data is not used in
        training and stays private. More here: https://trust.openai.com/
      </li>
      <li>
        You can view your estimated OpenAI usage cost in the Recenter settings.
      </li>
    </ul>
    <div>
      <strong>Data Sharing and Security</strong>
    </div>
    Recenter does not collect any personally identifiable information about you.
    We do not sell or share your browsing data with any third parties. All data
    is stored locally in your browser only. All data is stored locally in your
    browser only.
    <div>
      <strong>Data Retention</strong>
    </div>
    Your browsing data, categories, and text summaries are retained locally in
    your browser until you uninstall Recenter or clear your browsing data. We do
    not retain this data or have any plans to monetize it in the future.
    <div>
      <strong>Your Privacy Controls</strong>
    </div>
    You can review and delete your browsing data stored by Recenter at any time
    in the extension settings. Uninstalling Recenter will remove
    all local data.
    <div>
      <strong>Contact Us</strong>
    </div>
    If you have any other questions about this policy or Recenter's data
    practices, please contact us at sai@comini.in.
  </>
);
